
import type { UserProfile, Moment, ChatConversation, ChatMessage, ProfilePrompt, CrossedPathUser, Achievement, Challenge, Hotspot } from './types';

export const MOCK_USER_ID = 'user-123';

export const AVAILABLE_PROMPTS: ProfilePrompt[] = [
  { id: 'p1', question: 'About Me: Unusual Skills' },
  { id: 'p2', question: 'Typical Sunday' },
  { id: 'p3', question: 'A Random Fact I love is' },
  { id: 'p4', question: 'My Greatest Strength' },
  { id: 'p5', question: 'My Simple Pleasures' },
  { id: 'p6', question: 'I recently discovered that' },
  { id: 'p7', question: 'Dating me is like' },
  { id: 'p8', question: 'My most irrational fear' },
  { id: 'p9', question: 'This year, I really want to' },
  { id: 'p10', question: 'The Way to win me over is' },
  { id: 'p11', question: 'I go crazy for' },
  { id: 'p12', question: 'A life goal of mine' },
];

export const baseDate = new Date('2024-05-24T12:00:00.000Z'); 

const daysAgo = (days: number, hours = 0, minutes = 0) =>
  new Date(baseDate.getTime() - (days * 24 * 60 * 60 * 1000) - (hours * 60 * 60 * 1000) - (minutes * 60 * 1000)).toISOString();

const MOCK_ACHIEVEMENTS_FOR_CURRENT_USER: Achievement[] = [
  {
    id: 'achieve-1',
    name: 'Daily Logger',
    type: 'Streak',
    description: 'Logged a Moment 3 days in a row.',
    icon: 'Flame',
    achievedDate: daysAgo(1),
    rewards: ['🔓 Preview a Hidden Like'],
    glowEffect: false,
  },
  {
    id: 'achieve-2',
    name: 'Quick Responder',
    type: 'Prompt Sprint',
    description: 'Replied to 3 Moment Matches in 24 hours.',
    icon: 'Zap',
    achievedDate: daysAgo(5),
    rewards: ['Priority Visibility: Shown first in Explore.'],
  },
  {
    id: 'achieve-3',
    name: 'Urban Explorer',
    type: 'Explorer',
    description: 'Visited 3 different neighborhoods in a week.',
    icon: 'Compass',
    achievedDate: daysAgo(2),
    rewards: ['🎁 Echo Replay Token'],
  },
  {
    id: 'achieve-4',
    name: 'Fast Connection',
    type: 'Double Spark',
    description: 'Matched + started a conversation in under 2 hours.',
    icon: 'Sparkles',
    achievedDate: daysAgo(10),
    rewards: ['🌟 6-Hour Boosted Glow'],
    glowEffect: true,
  },
  {
    id: 'achieve-5',
    name: 'Profile Polisher',
    type: 'Profile Completion',
    description: 'Filled out all profile sections (bio, prompts, photos).',
    icon: 'UserCheck',
    achievedDate: daysAgo(15),
    rewards: ['Slight boost in profile visibility.'],
    glowEffect: false,
  },
];

export const MOCK_AVAILABLE_CHALLENGES: Challenge[] = [
  {
    id: 'challenge-1',
    name: 'Moment Marathon',
    type: 'Streak',
    description: 'Log a Moment 7 days in a row.',
    icon: 'CalendarCheck2',
    rewardPreview: 'Exclusive "Marathoner" Badge, 1 Week Crossd+ Trial',
    progress: { current: MOCK_ACHIEVEMENTS_FOR_CURRENT_USER.find(a => a.id === 'achieve-1') ? 3 : 1, target: 7, unit: 'days logged' },
    status: 'active',
    timeLimit: 'Ongoing',
    triggerAction: 'LOGGED_MOMENT',
  },
  {
    id: 'challenge-2',
    name: 'Chatterbox Champ',
    type: 'Timed Challenge',
    description: 'Reply to 5 Moment Matches within 48 hours of matching.',
    icon: 'MessageCircleReply',
    rewardPreview: '5 Free Super Likes, "Chatterbox" Badge',
    progress: { current: 1, target: 5, unit: 'matches replied' },
    status: 'active',
    timeLimit: '48 hours per match',
    triggerAction: 'REPLIED_TO_MATCH',
  },
  {
    id: 'challenge-3',
    name: 'City Navigator',
    type: 'Exploration',
    description: 'Visit and log Moments in 5 distinct boroughs or districts this month.',
    icon: 'Globe',
    rewardPreview: '"Navigator" Badge, Map Theme for Profile',
    progress: { current: 2, target: 5, unit: 'districts visited' },
    status: 'not_started',
    timeLimit: 'Ends this month',
    triggerAction: 'LOGGED_MOMENT_NEW_DISTRICT',
  },
  {
    id: 'challenge-4',
    name: 'Serendipity Seeker',
    type: 'Connection',
    description: 'Achieve 3 "Double Spark" matches (match + convo < 2hrs).',
    icon: 'HeartHandshake',
    rewardPreview: '"Serendipity" Badge, Extended Chat Features',
    progress: { current: MOCK_ACHIEVEMENTS_FOR_CURRENT_USER.find(a => a.id === 'achieve-4') ? 1 : 0, target: 3, unit: 'double sparks' },
    status: 'active',
    triggerAction: 'QUICK_MATCH_AND_CHAT',
  },
];


export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Alex',
    age: 28,
    gender: 'man',
    interestedIn: 'women',
    email: 'alex@example.com',
    bio: 'Loves hiking, coffee, and indie music. Always up for an adventure or a quiet night in with a good book.',
    images: [
      'https://placehold.co/400x550.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/500x500.png',
      'https://placehold.co/450x600.png',
      'https://placehold.co/700x450.png',
    ],
    vibeTags: ['adventurous', 'bookworm', 'coffee lover', 'calm', 'indie music enthusiast', 'mountain hiker', 'thoughtful conversations'],
    locationPatterns: ['downtown cafes', 'mountain trails', 'city parks', 'indie bookstores', 'record shops'],
    prompts: [
      { promptId: 'p1', answer: 'Pineapple belongs on pizza, fight me.' },
      { promptId: 'p2', answer: 'If animals could talk, which would be the rudest?' },
    ],
    work: 'Graphic Designer',
    jobTitle: 'Senior Designer',
    education: 'State University - BFA Design',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'11\"",
    locationAddress: "123 Main St, Anytown, USA",
    locationName: "Anytown",
    locationCoordinates: { lat: 40.7128, lng: -74.0060 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Aries",
    mbtiType: 'ENFP',
    idealMbtiType: 'INTJ',
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-2',
    name: 'Jamie',
    age: 25,
    gender: 'woman',
    interestedIn: 'men',
    email: 'jamie@example.com',
    bio: 'Artist, foodie, and travel enthusiast. Exploring new cultures and cuisines is my passion.',
    images: [
      'https://placehold.co/420x580.png',
      'https://placehold.co/750x500.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/500x700.png',
    ],
    vibeTags: ['creative', 'foodie', 'globetrotter', 'energetic', 'gallery hopper', 'street art admirer', 'spice fanatic'],
    locationPatterns: ['art galleries', 'international food markets', 'airport lounges', 'hidden gem eateries', 'photography walks'],
    prompts: [
      { promptId: 'p3', answer: 'Someone who appreciates art and isn\'t afraid to try new foods.' },
      { promptId: 'p5', answer: 'By making me laugh until my stomach hurts.' },
    ],
    work: 'Freelance Photographer',
    jobTitle: 'Photographer',
    education: 'Art Institute - Photography',
    ethnicity: 'Hispanic/Latino',
    childrenStatus: "Have Children",
    familyPlans: "Want children",
    height: "5'7\"",
    locationAddress: "456 Art Ave, Creative City, USA",
    locationName: "Creative City",
    locationCoordinates: { lat: 34.0522, lng: -118.2437 },
    drinking: "Yes",
    smoking: "Sometimes",
    zodiacSign: "Gemini",
    mbtiType: 'ISFP',
    idealMbtiType: 'ESTP',
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-3',
    name: 'Casey',
    age: 30,
    gender: 'non-binary',
    interestedIn: 'everyone',
    email: 'casey@example.com',
    bio: 'Tech geek, gamer, and animal lover. Fluent in sarcasm and Python.',
    images: [
      'https://placehold.co/450x600.png',
      'https://placehold.co/650x650.png',
      'https://placehold.co/800x500.png',
    ],
    vibeTags: ['techy', 'gamer', 'animal lover', 'witty', 'board game strategist', 'puzzle solver', 'pet cafe visitor'],
    locationPatterns: ['tech hubs', 'dog parks', 'retro arcades', 'escape rooms', 'hardware stores'],
    prompts: [
      { promptId: 'p4', answer: 'I\'ve skydived. I own 5 cats. I hate chocolate. (Lie: I hate chocolate)' },
    ],
    work: 'Software Engineer',
    jobTitle: 'Lead Developer',
    education: 'Tech University - BS Computer Science',
    ethnicity: 'East Asian',
    childrenStatus: "Prefer Not to Say",
    familyPlans: "Don't want children",
    height: "6'1\"",
    locationAddress: "789 Tech Rd, Silicon Valley, USA",
    locationName: "Silicon Valley",
    locationCoordinates: { lat: 37.3875, lng: -122.0575 },
    drinking: "No",
    smoking: "Prefer Not to Say",
    zodiacSign: "Scorpio",
    mbtiType: 'INTP',
    idealMbtiType: 'ENTJ',
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: MOCK_USER_ID, 
    name: 'Morgan',
    age: 29,
    gender: 'woman',
    interestedIn: 'everyone',
    email: 'morgan.dev@example.com',
    bio: "Just a dev user testing things out. I enjoy a good cup of coffee, exploring new tech, and weekend hikes. Let's see if our paths cross!",
    images: [
        'https://placehold.co/400x550.png',
        'https://placehold.co/600x800.png',
        'https://placehold.co/800x600.png',
        'https://placehold.co/500x700.png',
        'https://placehold.co/700x500.png',
        'https://placehold.co/650x650.png',
    ],
    vibeTags: ['coffee lover ☕️', 'techy 💻', 'hiking 🏔️', 'optimist 😊'],
    locationPatterns: ['downtown cafes', 'tech hubs', 'mountain trails'],
    prompts: [
        { promptId: 'p2', answer: 'A typical Sunday for me involves a slow morning with coffee and code, followed by an afternoon hike if the weather is good.' },
        { promptId: 'p5', answer: 'The smell of rain, finding a new favorite song, and a perfectly compiled piece of code.' },
    ],
    work: 'Firebase',
    jobTitle: 'App Prototyper',
    education: 'University of Code',
    ethnicity: 'Prefer Not to Say',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'10\"",
    locationAddress: '123 Main St, San Francisco, CA',
    locationName: 'San Francisco',
    locationCoordinates: { lat: 37.7749, lng: -122.4194 },
    drinking: 'Sometimes',
    smoking: 'No',
    zodiacSign: 'Aquarius',
    mbtiType: 'INTP',
    idealMbtiType: 'ENTP',
    achievements: MOCK_ACHIEVEMENTS_FOR_CURRENT_USER,
    onboardingComplete: true,
  },
  {
    id: 'user-4',
    name: 'Riley',
    age: 26,
    gender: 'man',
    interestedIn: 'women',
    email: 'riley.dev@example.com',
    bio: 'Software developer by day, nature explorer by weekend. Love strategy board games and finding hidden trails. Looking for someone to share adventures with.',
    images: [
      'https://placehold.co/430x570.png',
      'https://placehold.co/700x500.png',
      'https://placehold.co/650x750.png',
    ],
    vibeTags: ['tech enthusiast', 'nature lover', 'board games', 'hiking', 'problem solver', 'craft beer', 'stargazing'],
    locationPatterns: ['national parks', 'board game cafes', 'tech meetups', 'local breweries', 'scenic overlooks', 'mountain summits', 'campgrounds'],
    prompts: [
      { promptId: 'p6', answer: 'That otters hold hands when they sleep so they don\'t float away from each other.' },
      { promptId: 'p9', answer: 'Learn a new programming language and visit a new national park.' },
    ],
    work: 'Code Crafters Ltd.',
    jobTitle: 'Full Stack Developer',
    education: 'MIT',
    ethnicity: 'Other',
    childrenStatus: "Don't have children",
    familyPlans: "Want children",
    height: "5'10\"",
    locationAddress: "101 Binary Blvd, Techtopia, USA",
    locationName: "Techtopia",
    locationCoordinates: { lat: 37.4220, lng: -122.0841 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Aquarius",
    mbtiType: 'ISTP',
    idealMbtiType: 'ESFP',
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-5',
    name: 'Morgan',
    age: 29,
    gender: 'woman',
    interestedIn: 'men',
    email: 'morgan.art@example.com',
    bio: 'Painter and musician. I find beauty in everyday chaos. Often found at farmers markets or sketching in a park. My ideal date involves live music and good conversation.',
    images: [
      'https://placehold.co/390x510.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/500x700.png',
    ],
    vibeTags: ['artist', 'musician', 'farmers market regular', 'live music aficionado', 'sketchbook always', 'vintage lover', 'deep conversations'],
    locationPatterns: ['art supply stores', 'live music venues', 'local farmers markets', 'botanical gardens', 'indie cinemas', 'antique shops', 'poetry slams'],
    prompts: [
      { promptId: 'p2', answer: 'A long brunch, followed by a stroll through a flea market, and ending with some live jazz.' },
      { promptId: 'p7', answer: 'A collaborative art project that sometimes gets a little messy but is always beautiful.' },
    ],
    work: 'Self-Employed Artist',
    jobTitle: 'Painter & Illustrator',
    education: 'Rhode Island School of Design',
    ethnicity: 'Black/African Descent',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'6\"",
    locationAddress: "23 Palette Place, Artville, USA",
    locationName: "Artville",
    locationCoordinates: { lat: 41.8240, lng: -71.4128 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Pisces",
    mbtiType: 'INFP',
    idealMbtiType: 'ENFJ',
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-6',
    name: 'Jordan',
    age: 31,
    gender: 'man',
    interestedIn: 'women',
    email: 'jordan.fit@example.com',
    bio: 'Fitness enthusiast and world traveler. Always planning the next trip or the next workout. Looking for a partner in crime for adventures and gym sessions.',
    images: [
      'https://placehold.co/410x560.png',
      'https://placehold.co/750x550.png',
      'https://placehold.co/480x680.png',
    ],
    vibeTags: ['fitness junkie', 'travel bug', 'adventure seeker', 'gym regular', 'mountain climber', 'foodie (healthy)', 'optimistic'],
    locationPatterns: ['gyms & fitness studios', 'hiking trails', 'airports', 'healthy eateries', 'rock climbing centers', 'marathon routes', 'international hostels'],
    prompts: [
      { promptId: 'p4', answer: 'My resilience and ability to make friends anywhere.' },
      { promptId: 'p12', answer: 'To visit every continent and run a marathon in at least three of them.' },
    ],
    work: 'Global Adventures Inc.',
    jobTitle: 'Travel Consultant & Fitness Coach',
    education: 'University of Colorado Boulder',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Have Children",
    familyPlans: "Want children",
    height: "6'0\"",
    locationAddress: "7 Summit Street, Adventure Bay, USA",
    locationName: "Adventure Bay",
    locationCoordinates: { lat: 39.7392, lng: -104.9903 },
    drinking: "Yes",
    smoking: "No",
    zodiacSign: "Sagittarius",
    mbtiType: 'ESTJ',
    idealMbtiType: 'ISFJ',
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-7',
    name: 'Taylor',
    age: 24,
    gender: 'woman',
    interestedIn: 'men',
    email: 'taylor@example.com',
    bio: 'Musician and songwriter. Love playing guitar and discovering new coffee shops. Vinyl collector.',
    images: ['https://placehold.co/400x560.png', 'https://placehold.co/600x450.png'],
    vibeTags: ['musician', 'songwriter', 'coffee lover', 'vinyl', 'acoustic'],
    locationPatterns: ['coffee shops', 'music stores', 'open mic nights'],
    prompts: [{ promptId: 'p10', answer: 'Show me your favorite record.' }],
    work: 'Local Cafe',
    jobTitle: 'Barista & Musician',
    education: 'Community College - Music Theory',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'8\"",
    locationAddress: "10 Music Row, Nashville, USA",
    locationName: "Nashville",
    locationCoordinates: { lat: 36.1627, lng: -86.7816 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Libra",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-8',
    name: 'Chris',
    age: 33,
    gender: 'man',
    interestedIn: 'women',
    email: 'chris.chef@example.com',
    bio: 'Professional chef. Passionate about sustainable food and local ingredients. Likes cycling and documentaries.',
    images: ['https://placehold.co/420x570.png', 'https://placehold.co/700x500.png'],
    vibeTags: ['chef', 'foodie', 'sustainable', 'cycling', 'documentaries'],
    locationPatterns: ['farmers markets', 'restaurant kitchens', 'bike trails'],
    prompts: [{ promptId: 'p11', answer: 'Perfectly ripe avocados.' }],
    work: 'The Green Table Restaurant',
    jobTitle: 'Head Chef',
    education: 'Culinary Institute of America',
    ethnicity: 'Black/African Descent',
    childrenStatus: "Don't have children",
    familyPlans: "Want children",
    height: "6'2\"",
    locationAddress: "20 Gourmet Lane, Foodie Town, USA",
    locationName: "Foodie Town",
    locationCoordinates: { lat: 34.0522, lng: -118.2437 }, 
    drinking: "Yes",
    smoking: "No",
    zodiacSign: "Taurus",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-9',
    name: 'Sam',
    age: 29,
    gender: 'woman',
    interestedIn: 'men',
    email: 'sam.reads@example.com',
    bio: 'Librarian and avid reader. Enjoys historical fiction and quiet evenings. Volunteers at an animal shelter.',
    images: ['https://placehold.co/380x520.png', 'https://placehold.co/550x450.png'],
    vibeTags: ['bookworm', 'librarian', 'quiet', 'animal lover', 'history buff'],
    locationPatterns: ['libraries', 'bookstores', 'animal shelters', 'museums'],
    prompts: [{ promptId: 'p5', answer: 'A cup of tea and a good book.' }],
    work: 'City Central Library',
    jobTitle: 'Librarian',
    education: 'University of Washington - MLIS',
    ethnicity: 'South Asian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'5\"",
    locationAddress: "30 Chapter Ave, Bookish City, USA",
    locationName: "Bookish City",
    locationCoordinates: { lat: 47.6062, lng: -122.3321 }, 
    drinking: "No",
    smoking: "No",
    zodiacSign: "Virgo",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-10',
    name: 'Pat',
    age: 27,
    gender: 'non-binary',
    interestedIn: 'everyone',
    email: 'pat.codes@example.com',
    bio: 'UX Designer focused on accessibility. Loves bouldering and trying new craft beers. Weekend photographer.',
    images: ['https://placehold.co/410x550.png', 'https://placehold.co/650x480.png'],
    vibeTags: ['ux designer', 'accessibility', 'bouldering', 'craft beer', 'photography'],
    locationPatterns: ['climbing gyms', 'breweries', 'design meetups', 'city parks'],
    prompts: [{ promptId: 'p8', answer: 'Running out of battery on my camera during a perfect shot.' }],
    work: 'Innovatech Solutions',
    jobTitle: 'UX Designer',
    education: 'Carnegie Mellon - HCI',
    ethnicity: 'Other',
    childrenStatus: "Don't have children",
    familyPlans: "Want children",
    height: "5'9\"",
    locationAddress: "40 Design Drive, Interface City, USA",
    locationName: "Interface City",
    locationCoordinates: { lat: 40.4406, lng: -79.9959 }, 
    drinking: "Yes",
    smoking: "No",
    zodiacSign: "Cancer",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-11',
    name: 'Jess',
    age: 22,
    gender: 'woman',
    interestedIn: 'men',
    email: 'jess.studies@example.com',
    bio: 'University student studying environmental science. Passionate about conservation and enjoys hiking and camping.',
    images: ['https://placehold.co/390x530.png', 'https://placehold.co/600x500.png'],
    vibeTags: ['student', 'environmentalist', 'conservation', 'hiking', 'camping'],
    locationPatterns: ['university campus', 'national parks', 'nature reserves'],
    prompts: [{ promptId: 'p9', answer: 'To participate in a major conservation project.' }],
    work: 'State University (Student)',
    jobTitle: 'Student',
    education: 'State University - Environmental Science',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'6\"",
    locationAddress: "50 Campus Green, University Town, USA",
    locationName: "University Town",
    locationCoordinates: { lat: 38.9897, lng: -76.9378 }, 
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Leo",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-12',
    name: 'Drew',
    age: 35,
    gender: 'man',
    interestedIn: 'women',
    email: 'drew.builds@example.com',
    bio: 'Architect with a love for minimalist design. Enjoys sketching cityscapes and visiting art galleries. Learning pottery.',
    images: ['https://placehold.co/430x580.png', 'https://placehold.co/720x520.png'],
    vibeTags: ['architect', 'minimalist', 'design', 'art lover', 'pottery'],
    locationPatterns: ['architecture firms', 'art galleries', 'museums', 'pottery studios'],
    prompts: [{ promptId: 'p1', answer: 'Can perfectly fold a fitted sheet.' }],
    work: 'Modern Design Group',
    jobTitle: 'Architect',
    education: 'Harvard GSD',
    ethnicity: 'East Asian',
    childrenStatus: "Have Children",
    familyPlans: "Don't want children",
    height: "6'0\"",
    locationAddress: "60 Structure St, Design District, USA",
    locationName: "Design District",
    locationCoordinates: { lat: 42.3736, lng: -71.1097 }, 
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Capricorn",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-13',
    name: 'Charlie',
    age: 28,
    gender: 'man',
    interestedIn: 'women',
    email: 'charlie.travels@example.com',
    bio: 'Travel blogger and photographer. Always on the move, looking for the next adventure. Fluent in three languages.',
    images: ['https://placehold.co/400x550.png', 'https://placehold.co/800x550.png'],
    vibeTags: ['travel blogger', 'photographer', 'adventurous', 'multilingual', 'globetrotter'],
    locationPatterns: ['airports', 'hostels', 'famous landmarks', 'remote villages'],
    prompts: [{ promptId: 'p6', answer: 'That there are more stars in the universe than grains of sand on all Earth\'s beaches.' }],
    work: 'Nomad Ventures',
    jobTitle: 'Blogger & Photographer',
    education: 'NYU - Journalism',
    ethnicity: 'Hispanic/Latino',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'10\"",
    locationAddress: "70 Wanderlust Way, Global City, USA",
    locationName: "Global City",
    locationCoordinates: { lat: 40.7128, lng: -74.0060 }, 
    drinking: "Yes",
    smoking: "Sometimes",
    zodiacSign: "Sagittarius",
    achievements: [],
    onboardingComplete: true,
  },
  {
    id: 'user-14',
    name: 'Billie',
    age: 26,
    gender: 'woman',
    interestedIn: 'men',
    email: 'billie.codes@example.com',
    bio: 'Game developer and VR enthusiast. Loves sci-fi movies and building worlds. Trying to learn Japanese.',
    images: ['https://placehold.co/420x560.png', 'https://placehold.co/680x490.png'],
    vibeTags: ['game dev', 'vr', 'sci-fi', 'world builder', 'language learner'],
    locationPatterns: ['game studios', 'vr arcades', 'tech conventions', 'sci-fi movie screenings'],
    prompts: [{ promptId: 'p2', answer: 'Coding a personal project, then a long gaming session.' }],
    work: 'Pixel Perfect Games',
    jobTitle: 'Game Developer',
    education: 'DigiPen Institute',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Prefer Not to Say",
    familyPlans: "Want children",
    height: "5'7\"",
    locationAddress: "80 Pixel Pl, Gamer Grid, USA",
    locationName: "Gamer Grid",
    locationCoordinates: { lat: 37.7749, lng: -122.4194 }, 
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Aquarius",
    achievements: [],
    onboardingComplete: true,
  },
  // New Male Users
  {
    id: 'user-15',
    name: 'Liam Wilson',
    age: 29,
    gender: 'man',
    interestedIn: 'women',
    email: 'liam.wilson@example.com',
    bio: 'Charismatic leader who loves inspiring others. Let\'s build something amazing together. Coffee enthusiast and loves a good debate.',
    images: ['https://placehold.co/400x550.png'],
    vibeTags: ['leader', 'coffee lover', 'energetic', 'optimist'],
    locationPatterns: ['coffee shops', 'co-working spaces', 'conference halls'],
    prompts: [],
    work: 'Startup Founder',
    jobTitle: 'CEO',
    education: 'Stanford University',
    mbtiType: 'ENFJ',
    onboardingComplete: true,
  },
  {
    id: 'user-16',
    name: 'Noah Smith',
    age: 32,
    gender: 'man',
    interestedIn: 'women',
    email: 'noah.smith@example.com',
    bio: 'Practical and dependable. My word is my bond. Enjoy woodworking and long, quiet drives.',
    images: ['https://placehold.co/410x560.png'],
    vibeTags: ['dependable', 'woodworking', 'calm', 'loyal'],
    locationPatterns: ['hardware stores', 'country roads', 'local parks'],
    prompts: [],
    work: 'Construction Manager',
    jobTitle: 'Manager',
    education: 'Texas A&M',
    mbtiType: 'ISTJ',
    onboardingComplete: true,
  },
  {
    id: 'user-17',
    name: 'Oliver Jones',
    age: 27,
    gender: 'man',
    interestedIn: 'everyone',
    email: 'oliver.jones@example.com',
    bio: 'Life of the party. I live for spontaneity and new experiences. Let\'s make some memories.',
    images: ['https://placehold.co/420x570.png'],
    vibeTags: ['spontaneous', 'energetic', 'adventurous', 'social butterfly'],
    locationPatterns: ['concert venues', 'bars', 'sports stadiums'],
    prompts: [],
    work: 'Sales Executive',
    jobTitle: 'Executive',
    education: 'University of Miami',
    mbtiType: 'ESTP',
    onboardingComplete: true,
  },
  // New Female Users
  {
    id: 'user-18',
    name: 'Olivia Brown',
    age: 28,
    gender: 'woman',
    interestedIn: 'men',
    email: 'olivia.brown@example.com',
    bio: 'Idealistic and passionate about making the world a better place. I love deep conversations and rainy days.',
    images: ['https://placehold.co/430x580.png'],
    vibeTags: ['idealist', 'passionate', 'dreamer', 'bookworm'],
    locationPatterns: ['bookstores', 'art museums', 'volunteer centers'],
    prompts: [],
    work: 'Non-profit Coordinator',
    jobTitle: 'Coordinator',
    education: 'UC Berkeley',
    mbtiType: 'INFP',
    onboardingComplete: true,
  },
  {
    id: 'user-19',
    name: 'Emma Davis',
    age: 30,
    gender: 'woman',
    interestedIn: 'men',
    email: 'emma.davis@example.com',
    bio: 'Caring and organized. I love hosting dinner parties and making sure everyone feels welcome. My dog is my world.',
    images: ['https://placehold.co/440x590.png'],
    vibeTags: ['caring', 'organized', 'hostess', 'dog lover'],
    locationPatterns: ['home goods stores', 'dog parks', 'local markets'],
    prompts: [],
    work: 'Human Resources Manager',
    jobTitle: 'HR Manager',
    education: 'University of Illinois',
    mbtiType: 'ESFJ',
    onboardingComplete: true,
  },
  {
    id: 'user-20',
    name: 'Ava Miller',
    age: 25,
    gender: 'woman',
    interestedIn: 'everyone',
    email: 'ava.miller@example.com',
    bio: 'Strategic thinker with a love for complex problems. I have a plan for everything. Looking for an intellectual equal.',
    images: ['https://placehold.co/450x600.png'],
    vibeTags: ['strategic', 'intellectual', 'independent', 'visionary'],
    locationPatterns: ['libraries', 'chess clubs', 'lecture halls'],
    prompts: [],
    work: 'Data Scientist',
    jobTitle: 'Scientist',
    education: 'MIT',
    mbtiType: 'INTJ',
    onboardingComplete: true,
  },
];


export const MOCK_MOMENTS: Moment[] = [
  {
    id: 'moment-recap-1',
    loggerId: MOCK_USER_ID,
    placeName: 'The Shard',
    locationAddress: '32 London Bridge St, London',
    loggedAt: daysAgo(1, 2, 30), 
    potentialMatchId: 'user-1',
    coordinates: { lat: 51.5045, lng: -0.0865 },
    status: 'pending',
    momentDescription: "The view was incredible, and I noticed someone with a great sense of style near the window.",
    descriptors: {
      ethnicity: 'White/Caucasian',
      hairColour: 'Blonde',
      otherDetails: 'Wearing a cool leather jacket.'
    }
  },
  {
    id: 'moment-recap-2',
    loggerId: MOCK_USER_ID,
    placeName: 'Tower of London',
    locationAddress: 'London EC3N 4AB, United Kingdom',
    loggedAt: daysAgo(2, 5, 15), 
    coordinates: { lat: 51.5081, lng: -0.0759 },
    status: 'confirmed',
    momentDescription: "Fascinating history. Saw someone else who seemed just as captivated by the Crown Jewels.",
    descriptors: {
      ethnicity: 'East Asian',
      hairColour: 'Black',
      otherDetails: 'Had a camera and was taking really artistic shots.'
    }
  },
  {
    id: 'moment-recap-3',
    loggerId: MOCK_USER_ID,
    placeName: 'British Museum',
    locationAddress: 'Great Russell St, London',
    loggedAt: daysAgo(3, 1, 0), 
    potentialMatchId: 'user-2',
    coordinates: { lat: 51.5194, lng: -0.1270 },
    status: 'rejected',
    momentDescription: "Lost in the Egyptian exhibit. There was a quiet intensity about someone sketching near the Rosetta Stone.",
    descriptors: {
      ethnicity: 'Hispanic/Latino',
      hairColour: 'Brown',
      otherDetails: 'Carrying a Moleskine sketchbook.'
    }
  },
  {
    id: 'moment-recap-4',
    loggerId: MOCK_USER_ID,
    placeName: 'Tate Modern',
    locationAddress: 'Bankside, London SE1 9TG',
    loggedAt: daysAgo(4, 7, 0), 
    coordinates: { lat: 51.5076, lng: -0.0994 },
    status: 'pending',
    momentDescription: "The abstract art was moving. I shared a smile with someone who was also staring at a Rothko painting.",
    descriptors: {
      ethnicity: 'Black/African Descent',
      hairColour: 'Black',
      otherDetails: 'Wearing a very colorful headscarf.'
    }
  },
  {
    id: 'moment-recap-5',
    loggerId: MOCK_USER_ID,
    placeName: 'Borough Market',
    locationAddress: '8 Southwark St, London',
    loggedAt: daysAgo(5, -6, 0), 
    potentialMatchId: 'user-3',
    coordinates: { lat: 51.5055, lng: -0.0910 },
    status: 'pending',
    momentDescription: "The energy was amazing! So many great smells. Laughed with a stranger over a ridiculously large cheese wheel.",
    descriptors: {
      ethnicity: 'Prefer not to describe',
      hairColour: 'Other',
      otherDetails: 'They were wearing a band t-shirt I liked.'
    }
  },
  {
    id: 'moment-recap-6',
    loggerId: MOCK_USER_ID,
    placeName: 'Covent Garden',
    locationAddress: 'Covent Garden, London',
    loggedAt: daysAgo(0, 3, 0), 
    coordinates: { lat: 51.5118, lng: -0.1245 },
    status: 'pending',
    momentDescription: "Watching the street performers. Someone next to me had the most infectious laugh.",
    descriptors: {
      ethnicity: 'South Asian',
      hairColour: 'Brown',
      otherDetails: 'Had a really cool tote bag from an indie bookstore.'
    }
  },
  {
    id: 'moment-recap-7',
    loggerId: MOCK_USER_ID,
    placeName: 'Buckingham Palace',
    locationAddress: 'London SW1A 1AA, United Kingdom',
    loggedAt: daysAgo(6, 4, 0), 
    coordinates: { lat: 51.5014, lng: -0.1419 },
    status: 'pending',
    momentDescription: "Classic tourist moment. Saw someone else looking just as impressed by the guards.",
    descriptors: {
      ethnicity: 'White/Caucasian',
      hairColour: 'Red',
      otherDetails: 'Very smartly dressed.'
    }
  },
  {
    id: 'moment-old-1',
    loggerId: MOCK_USER_ID,
    placeName: 'Eiffel Tower',
    locationAddress: 'Champ de Mars, 5 Av. Anatole France',
    loggedAt: daysAgo(10),
    coordinates: { lat: 48.8584, lng: 2.2945 },
    status: 'pending',
    momentDescription: "A past memory from a trip to Paris. The sparkle at night is unforgettable.",
    descriptors: {
      ethnicity: 'Other',
      hairColour: 'Blonde',
      otherDetails: ''
    }
  },
  {
    id: 'moment-old-2',
    loggerId: MOCK_USER_ID,
    placeName: 'Golden Gate Bridge',
    locationAddress: 'Golden Gate Bridge, San Francisco, CA',
    loggedAt: daysAgo(25),
    coordinates: { lat: 37.8199, lng: -122.4783 },
    status: 'confirmed',
    momentDescription: "Walking across this was breathtaking. The fog rolled in perfectly.",
    descriptors: {
      ethnicity: 'East Asian',
      hairColour: 'Black',
      otherDetails: 'Had a professional-looking camera.'
    }
  },
  {
    id: 'moment-old-3',
    loggerId: MOCK_USER_ID,
    placeName: 'Central Park',
    locationAddress: 'New York, NY',
    loggedAt: daysAgo(40),
    coordinates: { lat: 40.785091, lng: -73.968285 },
    status: 'pending',
    momentDescription: "A lovely autumn walk. So peaceful in the middle of the city.",
    descriptors: {
      ethnicity: 'White/Caucasian',
      hairColour: 'Brown',
      otherDetails: 'Walking a very cute corgi.'
    }
  },
  {
    id: 'moment-1', 
    loggerId: 'user-4', 
    placeName: 'Montclair Art Museum',
    locationAddress: '3 S Mountain Ave, Montclair, NJ',
    loggedAt: daysAgo(8, 3, 30), 
    potentialMatchId: 'user-1',
    coordinates: { lat: 40.8137, lng: -74.2097 },
    status: 'pending',
    momentDescription: "The modern art wing was particularly striking today.",
    descriptors: {
      ethnicity: 'White/Caucasian',
      hairColour: 'Brown',
      otherDetails: 'Looked like a fellow creative.'
    }
  },
];


export const MOCK_CHAT_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'chat-1',
    participantIds: [MOCK_USER_ID, 'user-1'],
    participants: [
        MOCK_USERS.find(u => u.id === MOCK_USER_ID)!,
        MOCK_USERS.find(u => u.id === 'user-1')!
    ].map(p => ({id: p.id, name: p.name, images: p.images})),
    lastMessage: {
      text: 'Hey! Great to match with you.',
      timestamp: daysAgo(0, 0, 5),
      senderId: 'user-1',
    },
  },
  {
    id: 'chat-2',
    participantIds: [MOCK_USER_ID, 'user-2'],
    participants: [
        MOCK_USERS.find(u => u.id === MOCK_USER_ID)!,
        MOCK_USERS.find(u => u.id === 'user-2')!
    ].map(p => ({id: p.id, name: p.name, images: p.images})),
    lastMessage: {
      text: 'Loved your profile prompts! :)',
      timestamp: daysAgo(0, 0, 10),
      senderId: MOCK_USER_ID,
    },
  },
];

export const MOCK_CHAT_MESSAGES: { [chatId: string]: ChatMessage[] } = {
  'chat-1': [
    {
      id: 'msg-c1-1',
      chatId: 'chat-1',
      senderId: 'user-1',
      receiverId: MOCK_USER_ID,
      text: 'Hey! Great to match with you.',
      timestamp: daysAgo(0, 0, 5),
    },
    {
      id: 'msg-c1-2',
      chatId: 'chat-1',
      senderId: MOCK_USER_ID,
      receiverId: 'user-1',
      text: 'Hi Alex! Likewise. How\'s your day going?',
      timestamp: daysAgo(0, 0, 4),
    },
  ],
  'chat-2': [
    {
      id: 'msg-c2-1',
      chatId: 'chat-2',
      senderId: MOCK_USER_ID,
      receiverId: 'user-2',
      text: 'Loved your profile prompts! :)',
      timestamp: daysAgo(0, 0, 10),
    },
    {
      id: 'msg-c2-2',
      chatId: 'chat-2',
      senderId: 'user-2',
      receiverId: MOCK_USER_ID,
      text: 'Thanks! Yours too. That pineapple on pizza take is bold haha.',
      timestamp: daysAgo(0, 0, 9),
    },
     {
      id: 'msg-c2-3',
      chatId: 'chat-2',
      senderId: MOCK_USER_ID,
      receiverId: 'user-2',
      text: 'Haha, gotta stand by it! What kind of art do you do?',
      timestamp: daysAgo(0, 0, 8),
    },
  ],
};

export const getCurrentUser = (): UserProfile => {
  const user = MOCK_USERS.find(user => user.id === MOCK_USER_ID);
  if (!user) {
    // This is a fallback and should not be hit if MOCK_USER_ID is in MOCK_USERS
    return {
        id: MOCK_USER_ID,
        name: "Current User",
        age: 30,
        bio: "Default bio for a user not found in mock data.",
        images: ['https://placehold.co/400x500.png'],
        vibeTags: ["default", "user"],
        prompts: [],
        email: 'user@example.com',
        work: 'Unknown Inc.',
        jobTitle: 'Default Position',
        education: 'University of Defaults',
        ethnicity: 'Prefer Not to Say',
        childrenStatus: 'Prefer Not to Say',
        familyPlans: 'Prefer Not to Say',
        height: 'Prefer Not to Say',
        drinking: 'Prefer Not to Say',
        smoking: 'Prefer Not to Say',
        zodiacSign: 'Prefer Not to Say',
        locationAddress: '123 Default Street, Default City',
        locationName: 'Default City',
        locationCoordinates: { lat: 0, lng: 0 },
        achievements: [],
        locationPatterns: ['cafes', 'parks'],
        onboardingComplete: false,
    };
  }
  return user;
};

export const MOCK_CROSSED_PATHS_USERS: CrossedPathUser[] = MOCK_USERS.filter(u => u.id !== MOCK_USER_ID).map((user, index) => ({
  ...user,
  crossedAt: daysAgo(index + 0.1), 
  location: index % 3 === 0 ? 'The Shard' : (index % 3 === 1 ? 'Tate Modern' : 'British Museum'), 
}));

export const MOCK_HOTSPOTS: Hotspot[] = [
  {
    id: 'hs-1',
    type: 'Connection Zone',
    title: 'Sky Garden',
    description: 'A popular spot for first dates this week.',
    coordinates: { lat: 51.5108, lng: -0.0835 },
  },
  {
    id: 'hs-2',
    type: 'Serendipity Spike',
    title: 'Tower of London',
    description: 'This area had 2 Double Sparks today.',
    coordinates: { lat: 51.5081, lng: -0.0759 },
  },
  {
    id: 'hs-3',
    type: 'Loop Zone',
    title: 'The Gherkin',
    description: 'You’ve crossed paths with multiple users here before.',
    coordinates: { lat: 51.5145, lng: -0.0803 },
  },
];

export const MOCK_SPARK_SUGGESTIONS = [
  {
    id: 'spark-1',
    placeName: 'The Quiet Reader Cafe',
    type: 'Hidden Gem',
    vibe: 'Cozy & Chill',
    reason: 'Because you\'re an INFP who loves a good story, this quiet bookstore cafe is the perfect place to get lost in thought.',
    distance: '0.8 miles',
    imageUrl: 'https://placehold.co/600x400.png',
    coordinates: { lat: 51.515, lng: -0.128 },
  },
  {
    id: 'spark-2',
    placeName: 'The Electric Note Jazz Bar',
    type: 'High-Spark Spot',
    vibe: 'Live Music & Energetic',
    reason: 'Your ESTP energy thrives on excitement. This legendary music venue is where you\'ll find the city\'s best live acts.',
    distance: '2.1 miles',
    imageUrl: 'https://placehold.co/600x400.png',
    coordinates: { lat: 51.513, lng: -0.125 },
  },
  {
    id: 'spark-3',
    placeName: 'Gallery of Whispers',
    type: 'Creative Corner',
    vibe: 'Artistic & Thoughtful',
    reason: 'A perfect spot for an INTJ to appreciate complex art and find intellectual stimulation away from the crowds.',
    distance: '1.5 miles',
    imageUrl: 'https://placehold.co/600x400.png',
    coordinates: { lat: 51.508, lng: -0.098 },
  },
];
