
import type { UserProfile, Moment, ChatConversation, ChatMessage, ProfilePrompt, CrossedPathUser, Achievement, Challenge, Hotspot } from './types';
import { Flame, Zap, Compass, Sparkles, CalendarCheck2, MessageCircleReply, Globe, HeartHandshake, UserCheck, Target as TargetIcon } from 'lucide-react';

export const MOCK_USER_ID = 'user-123';

export const AVAILABLE_PROMPTS: ProfilePrompt[] = [
  { id: 'p1', question: 'About Me: Unusual Skills' },
  { id: 'p2', question: 'Typical Sunday' },
  { id: 'p3', question: 'A Random Fact I love is' },
  { id: 'p4', question: 'My Greatest Strength' },
  { id: 'p5', question: 'My Simple Pleasures' },
  { id: 'p6', question: 'I recently discovered that' },
  { id: 'p7', question: 'Dating me is like' },
  { id: 'p8', question: 'My most irrational fear' },
  { id: 'p9', question: 'This year, I really want to' },
  { id: 'p10', question: 'The Way to win me over is' },
  { id: 'p11', question: 'I go crazy for' },
  { id: 'p12', question: 'A life goal of mine' },
];

export const baseDate = new Date('2024-05-24T12:00:00.000Z'); 

const daysAgo = (days: number, hours = 0, minutes = 0) =>
  new Date(baseDate.getTime() - (days * 24 * 60 * 60 * 1000) - (hours * 60 * 60 * 1000) - (minutes * 60 * 1000)).toISOString();

const MOCK_ACHIEVEMENTS_FOR_CURRENT_USER: Achievement[] = [
  {
    id: 'achieve-1',
    name: 'Daily Logger',
    type: 'Streak',
    description: 'Logged a Moment 3 days in a row.',
    icon: Flame,
    achievedDate: daysAgo(1),
    rewards: ['🔓 Preview a Hidden Like'],
    glowEffect: false,
  },
  {
    id: 'achieve-2',
    name: 'Quick Responder',
    type: 'Prompt Sprint',
    description: 'Replied to 3 Moment Matches in 24 hours.',
    icon: Zap,
    achievedDate: daysAgo(5),
    rewards: ['Priority Visibility: Shown first in Explore.'],
  },
  {
    id: 'achieve-3',
    name: 'Urban Explorer',
    type: 'Explorer',
    description: 'Visited 3 different neighborhoods in a week.',
    icon: Compass,
    achievedDate: daysAgo(2),
    rewards: ['🎁 Echo Replay Token'],
  },
  {
    id: 'achieve-4',
    name: 'Fast Connection',
    type: 'Double Spark',
    description: 'Matched + started a conversation in under 2 hours.',
    icon: Sparkles,
    achievedDate: daysAgo(10),
    rewards: ['🌟 6-Hour Boosted Glow'],
    glowEffect: true,
  },
  {
    id: 'achieve-5',
    name: 'Profile Polisher',
    type: 'Profile Completion',
    description: 'Filled out all profile sections (bio, prompts, photos).',
    icon: UserCheck,
    achievedDate: daysAgo(15),
    rewards: ['Slight boost in profile visibility.'],
    glowEffect: false,
  },
];

export const MOCK_AVAILABLE_CHALLENGES: Challenge[] = [
  {
    id: 'challenge-1',
    name: 'Moment Marathon',
    type: 'Streak',
    description: 'Log a Moment 7 days in a row.',
    icon: CalendarCheck2,
    rewardPreview: 'Exclusive "Marathoner" Badge, 1 Week Crossd+ Trial',
    progress: { current: MOCK_ACHIEVEMENTS_FOR_CURRENT_USER.find(a => a.id === 'achieve-1') ? 3 : 1, target: 7, unit: 'days logged' }, // User has logged 3 days already if "Daily Logger" is achieved
    status: 'active',
    timeLimit: 'Ongoing',
  },
  {
    id: 'challenge-2',
    name: 'Chatterbox Champ',
    type: 'Timed Challenge',
    description: 'Reply to 5 Moment Matches within 48 hours of matching.',
    icon: MessageCircleReply,
    rewardPreview: '5 Free Super Likes, "Chatterbox" Badge',
    progress: { current: 1, target: 5, unit: 'matches replied' },
    status: 'active',
    timeLimit: '48 hours per match',
  },
  {
    id: 'challenge-3',
    name: 'City Navigator',
    type: 'Exploration',
    description: 'Visit and log Moments in 5 distinct boroughs or districts this month.',
    icon: Globe,
    rewardPreview: '"Navigator" Badge, Map Theme for Profile',
    progress: { current: 2, target: 5, unit: 'districts visited' },
    status: 'not_started',
    timeLimit: 'Ends this month',
  },
  {
    id: 'challenge-4',
    name: 'Serendipity Seeker',
    type: 'Connection',
    description: 'Achieve 3 "Double Spark" matches (match + convo < 2hrs).',
    icon: HeartHandshake,
    rewardPreview: '"Serendipity" Badge, Extended Chat Features',
    progress: { current: MOCK_ACHIEVEMENTS_FOR_CURRENT_USER.find(a => a.id === 'achieve-4') ? 1 : 0, target: 3, unit: 'double sparks' },
    status: 'active',
  },
];


export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Alex',
    age: 28,
    email: 'alex@example.com',
    bio: 'Loves hiking, coffee, and indie music. Always up for an adventure or a quiet night in with a good book.',
    images: [
      'https://placehold.co/400x550.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/500x500.png',
      'https://placehold.co/450x600.png',
      'https://placehold.co/700x450.png',
    ],
    vibeTags: ['adventurous', 'bookworm', 'coffee lover', 'calm', 'indie music enthusiast', 'mountain hiker', 'thoughtful conversations'],
    locationPatterns: ['downtown cafes', 'mountain trails', 'city parks', 'indie bookstores', 'record shops'],
    prompts: [
      { promptId: 'p1', answer: 'Pineapple belongs on pizza, fight me.' },
      { promptId: 'p2', answer: 'If animals could talk, which would be the rudest?' },
    ],
    work: 'Graphic Designer',
    jobTitle: 'Senior Designer',
    education: 'State University - BFA Design',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'11\"",
    locationAddress: "123 Main St, Anytown, USA",
    locationName: "Anytown",
    locationCoordinates: { lat: 40.7128, lng: -74.0060 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Aries",
    achievements: [],
  },
  {
    id: 'user-2',
    name: 'Jamie',
    age: 25,
    email: 'jamie@example.com',
    bio: 'Artist, foodie, and travel enthusiast. Exploring new cultures and cuisines is my passion.',
    images: [
      'https://placehold.co/420x580.png',
      'https://placehold.co/750x500.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/500x700.png',
    ],
    vibeTags: ['creative', 'foodie', 'globetrotter', 'energetic', 'gallery hopper', 'street art admirer', 'spice fanatic'],
    locationPatterns: ['art galleries', 'international food markets', 'airport lounges', 'hidden gem eateries', 'photography walks'],
    prompts: [
      { promptId: 'p3', answer: 'Someone who appreciates art and isn\'t afraid to try new foods.' },
      { promptId: 'p5', answer: 'By making me laugh until my stomach hurts.' },
    ],
    work: 'Freelance Photographer',
    jobTitle: 'Photographer',
    education: 'Art Institute - Photography',
    ethnicity: 'Hispanic/Latino',
    childrenStatus: "Have Children",
    familyPlans: "Want children",
    height: "5'7\"",
    locationAddress: "456 Art Ave, Creative City, USA",
    locationName: "Creative City",
    locationCoordinates: { lat: 34.0522, lng: -118.2437 },
    drinking: "Yes",
    smoking: "Sometimes",
    zodiacSign: "Gemini",
    achievements: [],
  },
  {
    id: 'user-3',
    name: 'Casey',
    age: 30,
    email: 'casey@example.com',
    bio: 'Tech geek, gamer, and animal lover. Fluent in sarcasm and Python.',
    images: [
      'https://placehold.co/450x600.png',
      'https://placehold.co/650x650.png',
      'https://placehold.co/800x500.png',
    ],
    vibeTags: ['techy', 'gamer', 'animal lover', 'witty', 'board game strategist', 'puzzle solver', 'pet cafe visitor'],
    locationPatterns: ['tech hubs', 'dog parks', 'retro arcades', 'escape rooms', 'hardware stores'],
    prompts: [
      { promptId: 'p4', answer: 'I\'ve skydived. I own 5 cats. I hate chocolate. (Lie: I hate chocolate)' },
    ],
    work: 'Software Engineer',
    jobTitle: 'Lead Developer',
    education: 'Tech University - BS Computer Science',
    ethnicity: 'East Asian',
    childrenStatus: "Prefer Not to Say",
    familyPlans: "Don't want children",
    height: "6'1\"",
    locationAddress: "789 Tech Rd, Silicon Valley, USA",
    locationName: "Silicon Valley",
    locationCoordinates: { lat: 37.3875, lng: -122.0575 },
    drinking: "No",
    smoking: "Prefer Not to Say",
    zodiacSign: "Scorpio",
    achievements: [],
  },
  {
    id: MOCK_USER_ID, 
    name: 'Dev User',
    age: 27,
    email: 'dev@example.com',
    bio: "Full-stack developer by day, aspiring chef by night! I love experimenting with new recipes, especially Italian and Thai. Weekends are for long bike rides, discovering hidden city gems, and maybe a bit of retro gaming. Seeking connections and new experiences. Love exploring local cafes and parks. My vibe tags are usually \"explorer\", \"optimist\", \"curious\", and \"friendly\". Let's see where our paths cross!",
    images: [
      'https://placehold.co/400x550.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/500x500.png',
      'https://placehold.co/450x600.png',
      'https://placehold.co/700x450.png',
    ],
    vibeTags: ['explorer', 'optimist', 'curious', 'friendly', 'coffee enthusiast', 'park lover'],
    locationPatterns: ['local coffee shops', 'bookstores', 'community gardens', 'farmers markets', 'museums', 'culinary schools', 'bike paths', 'retro arcades'],
    prompts: [
      { promptId: 'p1', answer: 'Early bird gets the worm, but the second mouse gets the cheese.' },
      { promptId: 'p3', answer: 'Someone genuine, kind, and open-minded.' },
    ],
    work: 'App Prototyper Inc.',
    jobTitle: 'AI Assistant',
    education: 'Firebase Studio University',
    ethnicity: 'Prefer Not to Say',
    childrenStatus: 'Prefer Not to Say',
    familyPlans: 'Prefer Not to Say',
    height: 'Prefer Not to Say',
    drinking: 'Prefer Not to Say',
    smoking: 'Prefer Not to Say',
    zodiacSign: 'Prefer Not to Say',
    locationAddress: '1 Developer Way, Firebase City, FS',
    locationName: 'Firebase City',
    locationCoordinates: { lat: 37.7749, lng: -122.4194 },
    achievements: MOCK_ACHIEVEMENTS_FOR_CURRENT_USER, 
  },
  {
    id: 'user-4',
    name: 'Riley',
    age: 26,
    email: 'riley.dev@example.com',
    bio: 'Software developer by day, nature explorer by weekend. Love strategy board games and finding hidden trails. Looking for someone to share adventures with.',
    images: [
      'https://placehold.co/430x570.png',
      'https://placehold.co/700x500.png',
      'https://placehold.co/650x750.png',
    ],
    vibeTags: ['tech enthusiast', 'nature lover', 'board games', 'hiking', 'problem solver', 'craft beer', 'stargazing'],
    locationPatterns: ['national parks', 'board game cafes', 'tech meetups', 'local breweries', 'scenic overlooks', 'mountain summits', 'campgrounds'],
    prompts: [
      { promptId: 'p6', answer: 'That otters hold hands when they sleep so they don\'t float away from each other.' },
      { promptId: 'p9', answer: 'Learn a new programming language and visit a new national park.' },
    ],
    work: 'Code Crafters Ltd.',
    jobTitle: 'Full Stack Developer',
    education: 'MIT',
    ethnicity: 'Other',
    childrenStatus: "Don't have children",
    familyPlans: "Want children",
    height: "5'10\"",
    locationAddress: "101 Binary Blvd, Techtopia, USA",
    locationName: "Techtopia",
    locationCoordinates: { lat: 37.4220, lng: -122.0841 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Aquarius",
    achievements: [],
  },
  {
    id: 'user-5',
    name: 'Morgan',
    age: 29,
    email: 'morgan.art@example.com',
    bio: 'Painter and musician. I find beauty in everyday chaos. Often found at farmers markets or sketching in a park. My ideal date involves live music and good conversation.',
    images: [
      'https://placehold.co/390x510.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/500x700.png',
    ],
    vibeTags: ['artist', 'musician', 'farmers market regular', 'live music aficionado', 'sketchbook always', 'vintage lover', 'deep conversations'],
    locationPatterns: ['art supply stores', 'live music venues', 'local farmers markets', 'botanical gardens', 'indie cinemas', 'antique shops', 'poetry slams'],
    prompts: [
      { promptId: 'p2', answer: 'A long brunch, followed by a stroll through a flea market, and ending with some live jazz.' },
      { promptId: 'p7', answer: 'A collaborative art project that sometimes gets a little messy but is always beautiful.' },
    ],
    work: 'Self-Employed Artist',
    jobTitle: 'Painter & Illustrator',
    education: 'Rhode Island School of Design',
    ethnicity: 'Black/African Descent',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'6\"",
    locationAddress: "23 Palette Place, Artville, USA",
    locationName: "Artville",
    locationCoordinates: { lat: 41.8240, lng: -71.4128 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Pisces",
    achievements: [],
  },
  {
    id: 'user-6',
    name: 'Jordan',
    age: 31,
    email: 'jordan.fit@example.com',
    bio: 'Fitness enthusiast and world traveler. Always planning the next trip or the next workout. Looking for a partner in crime for adventures and gym sessions.',
    images: [
      'https://placehold.co/410x560.png',
      'https://placehold.co/750x550.png',
      'https://placehold.co/480x680.png',
    ],
    vibeTags: ['fitness junkie', 'travel bug', 'adventure seeker', 'gym regular', 'mountain climber', 'foodie (healthy)', 'optimistic'],
    locationPatterns: ['gyms & fitness studios', 'hiking trails', 'airports', 'healthy eateries', 'rock climbing centers', 'marathon routes', 'international hostels'],
    prompts: [
      { promptId: 'p4', answer: 'My resilience and ability to make friends anywhere.' },
      { promptId: 'p12', answer: 'To visit every continent and run a marathon in at least three of them.' },
    ],
    work: 'Global Adventures Inc.',
    jobTitle: 'Travel Consultant & Fitness Coach',
    education: 'University of Colorado Boulder',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Have Children",
    familyPlans: "Want children",
    height: "6'0\"",
    locationAddress: "7 Summit Street, Adventure Bay, USA",
    locationName: "Adventure Bay",
    locationCoordinates: { lat: 39.7392, lng: -104.9903 },
    drinking: "Yes",
    smoking: "No",
    zodiacSign: "Sagittarius",
    achievements: [],
  },
  {
    id: 'user-7',
    name: 'Taylor',
    age: 24,
    email: 'taylor@example.com',
    bio: 'Musician and songwriter. Love playing guitar and discovering new coffee shops. Vinyl collector.',
    images: ['https://placehold.co/400x560.png', 'https://placehold.co/600x450.png'],
    vibeTags: ['musician', 'songwriter', 'coffee lover', 'vinyl', 'acoustic'],
    locationPatterns: ['coffee shops', 'music stores', 'open mic nights'],
    prompts: [{ promptId: 'p10', answer: 'Show me your favorite record.' }],
    work: 'Local Cafe',
    jobTitle: 'Barista & Musician',
    education: 'Community College - Music Theory',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'8\"",
    locationAddress: "10 Music Row, Nashville, USA",
    locationName: "Nashville",
    locationCoordinates: { lat: 36.1627, lng: -86.7816 },
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Libra",
    achievements: [],
  },
  {
    id: 'user-8',
    name: 'Chris',
    age: 33,
    email: 'chris.chef@example.com',
    bio: 'Professional chef. Passionate about sustainable food and local ingredients. Likes cycling and documentaries.',
    images: ['https://placehold.co/420x570.png', 'https://placehold.co/700x500.png'],
    vibeTags: ['chef', 'foodie', 'sustainable', 'cycling', 'documentaries'],
    locationPatterns: ['farmers markets', 'restaurant kitchens', 'bike trails'],
    prompts: [{ promptId: 'p11', answer: 'Perfectly ripe avocados.' }],
    work: 'The Green Table Restaurant',
    jobTitle: 'Head Chef',
    education: 'Culinary Institute of America',
    ethnicity: 'Black/African Descent',
    childrenStatus: "Don't have children",
    familyPlans: "Want children",
    height: "6'2\"",
    locationAddress: "20 Gourmet Lane, Foodie Town, USA",
    locationName: "Foodie Town",
    locationCoordinates: { lat: 34.0522, lng: -118.2437 }, 
    drinking: "Yes",
    smoking: "No",
    zodiacSign: "Taurus",
    achievements: [],
  },
  {
    id: 'user-9',
    name: 'Sam',
    age: 29,
    email: 'sam.reads@example.com',
    bio: 'Librarian and avid reader. Enjoys historical fiction and quiet evenings. Volunteers at an animal shelter.',
    images: ['https://placehold.co/380x520.png', 'https://placehold.co/550x450.png'],
    vibeTags: ['bookworm', 'librarian', 'quiet', 'animal lover', 'history buff'],
    locationPatterns: ['libraries', 'bookstores', 'animal shelters', 'museums'],
    prompts: [{ promptId: 'p5', answer: 'A cup of tea and a good book.' }],
    work: 'City Central Library',
    jobTitle: 'Librarian',
    education: 'University of Washington - MLIS',
    ethnicity: 'South Asian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'5\"",
    locationAddress: "30 Chapter Ave, Bookish City, USA",
    locationName: "Bookish City",
    locationCoordinates: { lat: 47.6062, lng: -122.3321 }, 
    drinking: "No",
    smoking: "No",
    zodiacSign: "Virgo",
    achievements: [],
  },
  {
    id: 'user-10',
    name: 'Pat',
    age: 27,
    email: 'pat.codes@example.com',
    bio: 'UX Designer focused on accessibility. Loves bouldering and trying new craft beers. Weekend photographer.',
    images: ['https://placehold.co/410x550.png', 'https://placehold.co/650x480.png'],
    vibeTags: ['ux designer', 'accessibility', 'bouldering', 'craft beer', 'photography'],
    locationPatterns: ['climbing gyms', 'breweries', 'design meetups', 'city parks'],
    prompts: [{ promptId: 'p8', answer: 'Running out of battery on my camera during a perfect shot.' }],
    work: 'Innovatech Solutions',
    jobTitle: 'UX Designer',
    education: 'Carnegie Mellon - HCI',
    ethnicity: 'Other',
    childrenStatus: "Don't have children",
    familyPlans: "Want children",
    height: "5'9\"",
    locationAddress: "40 Design Drive, Interface City, USA",
    locationName: "Interface City",
    locationCoordinates: { lat: 40.4406, lng: -79.9959 }, 
    drinking: "Yes",
    smoking: "No",
    zodiacSign: "Cancer",
    achievements: [],
  },
  {
    id: 'user-11',
    name: 'Jess',
    age: 22,
    email: 'jess.studies@example.com',
    bio: 'University student studying environmental science. Passionate about conservation and enjoys hiking and camping.',
    images: ['https://placehold.co/390x530.png', 'https://placehold.co/600x500.png'],
    vibeTags: ['student', 'environmentalist', 'conservation', 'hiking', 'camping'],
    locationPatterns: ['university campus', 'national parks', 'nature reserves'],
    prompts: [{ promptId: 'p9', answer: 'To participate in a major conservation project.' }],
    work: 'State University (Student)',
    jobTitle: 'Student',
    education: 'State University - Environmental Science',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'6\"",
    locationAddress: "50 Campus Green, University Town, USA",
    locationName: "University Town",
    locationCoordinates: { lat: 38.9897, lng: -76.9378 }, 
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Leo",
    achievements: [],
  },
  {
    id: 'user-12',
    name: 'Drew',
    age: 35,
    email: 'drew.builds@example.com',
    bio: 'Architect with a love for minimalist design. Enjoys sketching cityscapes and visiting art galleries. Learning pottery.',
    images: ['https://placehold.co/430x580.png', 'https://placehold.co/720x520.png'],
    vibeTags: ['architect', 'minimalist', 'design', 'art lover', 'pottery'],
    locationPatterns: ['architecture firms', 'art galleries', 'museums', 'pottery studios'],
    prompts: [{ promptId: 'p1', answer: 'Can perfectly fold a fitted sheet.' }],
    work: 'Modern Design Group',
    jobTitle: 'Architect',
    education: 'Harvard GSD',
    ethnicity: 'East Asian',
    childrenStatus: "Have Children",
    familyPlans: "Don't want children",
    height: "6'0\"",
    locationAddress: "60 Structure St, Design District, USA",
    locationName: "Design District",
    locationCoordinates: { lat: 42.3736, lng: -71.1097 }, 
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Capricorn",
    achievements: [],
  },
  {
    id: 'user-13',
    name: 'Charlie',
    age: 28,
    email: 'charlie.travels@example.com',
    bio: 'Travel blogger and photographer. Always on the move, looking for the next adventure. Fluent in three languages.',
    images: ['https://placehold.co/400x550.png', 'https://placehold.co/800x550.png'],
    vibeTags: ['travel blogger', 'photographer', 'adventurous', 'multilingual', 'globetrotter'],
    locationPatterns: ['airports', 'hostels', 'famous landmarks', 'remote villages'],
    prompts: [{ promptId: 'p6', answer: 'That there are more stars in the universe than grains of sand on all Earth\'s beaches.' }],
    work: 'Nomad Ventures',
    jobTitle: 'Blogger & Photographer',
    education: 'NYU - Journalism',
    ethnicity: 'Hispanic/Latino',
    childrenStatus: "Don't have children",
    familyPlans: "Not Sure",
    height: "5'10\"",
    locationAddress: "70 Wanderlust Way, Global City, USA",
    locationName: "Global City",
    locationCoordinates: { lat: 40.7128, lng: -74.0060 }, 
    drinking: "Yes",
    smoking: "Sometimes",
    zodiacSign: "Sagittarius",
    achievements: [],
  },
  {
    id: 'user-14',
    name: 'Billie',
    age: 26,
    email: 'billie.codes@example.com',
    bio: 'Game developer and VR enthusiast. Loves sci-fi movies and building worlds. Trying to learn Japanese.',
    images: ['https://placehold.co/420x560.png', 'https://placehold.co/680x490.png'],
    vibeTags: ['game dev', 'vr', 'sci-fi', 'world builder', 'language learner'],
    locationPatterns: ['game studios', 'vr arcades', 'tech conventions', 'sci-fi movie screenings'],
    prompts: [{ promptId: 'p2', answer: 'Coding a personal project, then a long gaming session.' }],
    work: 'Pixel Perfect Games',
    jobTitle: 'Game Developer',
    education: 'DigiPen Institute',
    ethnicity: 'White/Caucasian',
    childrenStatus: "Prefer Not to Say",
    familyPlans: "Want children",
    height: "5'7\"",
    locationAddress: "80 Pixel Pl, Gamer Grid, USA",
    locationName: "Gamer Grid",
    locationCoordinates: { lat: 37.7749, lng: -122.4194 }, 
    drinking: "Sometimes",
    smoking: "No",
    zodiacSign: "Aquarius",
    achievements: [],
  }
];


export const MOCK_MOMENTS: Moment[] = [
  {
    id: 'moment-recap-1',
    userId: MOCK_USER_ID,
    placeName: 'The Shard',
    timestamp: daysAgo(1, 2, 30), 
    potentialMatchId: 'user-1',
    coordinates: { lat: 51.5045, lng: -0.0865 },
  },
  {
    id: 'moment-recap-2',
    userId: MOCK_USER_ID,
    placeName: 'Tower of London',
    timestamp: daysAgo(2, 5, 15), 
    coordinates: { lat: 51.5081, lng: -0.0759 },
  },
  {
    id: 'moment-recap-3',
    userId: MOCK_USER_ID,
    placeName: 'British Museum',
    timestamp: daysAgo(3, 1, 0), 
    potentialMatchId: 'user-2',
    coordinates: { lat: 51.5194, lng: -0.1270 },
  },
  {
    id: 'moment-recap-4',
    userId: MOCK_USER_ID,
    placeName: 'Tate Modern',
    timestamp: daysAgo(4, 7, 0), 
    coordinates: { lat: 51.5076, lng: -0.0994 },
  },
  {
    id: 'moment-recap-5',
    userId: MOCK_USER_ID,
    placeName: 'Borough Market',
    timestamp: daysAgo(5, -6, 0), 
    potentialMatchId: 'user-3',
    coordinates: { lat: 51.5055, lng: -0.0910 },
  },
  {
    id: 'moment-recap-6',
    userId: MOCK_USER_ID,
    placeName: 'Covent Garden',
    timestamp: daysAgo(0, 3, 0), 
    coordinates: { lat: 51.5118, lng: -0.1245 },
  },
  {
    id: 'moment-recap-7',
    userId: MOCK_USER_ID,
    placeName: 'Buckingham Palace',
    timestamp: daysAgo(6, 4, 0), 
    coordinates: { lat: 51.5014, lng: -0.1419 },
  },
  {
    id: 'moment-old-1',
    userId: MOCK_USER_ID,
    placeName: 'Old Cafe Not in London',
    timestamp: daysAgo(10),
    coordinates: { lat: 40.8000, lng: -74.1900 },
  },
  {
    id: 'moment-1', 
    userId: 'user-4', 
    placeName: 'Original Montclair Art Museum',
    timestamp: daysAgo(8, 3, 30), 
    potentialMatchId: 'user-1',
    coordinates: { lat: 40.8137, lng: -74.2097 },
  },
];


export const MOCK_CHAT_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'chat-1',
    participantIds: [MOCK_USER_ID, 'user-1'],
    participants: [
        MOCK_USERS.find(u => u.id === MOCK_USER_ID)!,
        MOCK_USERS.find(u => u.id === 'user-1')!
    ].map(p => ({id: p.id, name: p.name, images: p.images})),
    lastMessage: {
      text: 'Hey! Great to match with you.',
      timestamp: daysAgo(0, 0, 5),
      senderId: 'user-1',
    },
  },
  {
    id: 'chat-2',
    participantIds: [MOCK_USER_ID, 'user-2'],
    participants: [
        MOCK_USERS.find(u => u.id === MOCK_USER_ID)!,
        MOCK_USERS.find(u => u.id === 'user-2')!
    ].map(p => ({id: p.id, name: p.name, images: p.images})),
    lastMessage: {
      text: 'Loved your profile prompts! :)',
      timestamp: daysAgo(0, 0, 10),
      senderId: MOCK_USER_ID,
    },
  },
];

export const MOCK_CHAT_MESSAGES: { [chatId: string]: ChatMessage[] } = {
  'chat-1': [
    {
      id: 'msg-c1-1',
      chatId: 'chat-1',
      senderId: 'user-1',
      receiverId: MOCK_USER_ID,
      text: 'Hey! Great to match with you.',
      timestamp: daysAgo(0, 0, 5),
    },
    {
      id: 'msg-c1-2',
      chatId: 'chat-1',
      senderId: MOCK_USER_ID,
      receiverId: 'user-1',
      text: 'Hi Alex! Likewise. How\'s your day going?',
      timestamp: daysAgo(0, 0, 4),
    },
  ],
  'chat-2': [
    {
      id: 'msg-c2-1',
      chatId: 'chat-2',
      senderId: MOCK_USER_ID,
      receiverId: 'user-2',
      text: 'Loved your profile prompts! :)',
      timestamp: daysAgo(0, 0, 10),
    },
    {
      id: 'msg-c2-2',
      chatId: 'chat-2',
      senderId: 'user-2',
      receiverId: MOCK_USER_ID,
      text: 'Thanks! Yours too. That pineapple on pizza take is bold haha.',
      timestamp: daysAgo(0, 0, 9),
    },
     {
      id: 'msg-c2-3',
      chatId: 'chat-2',
      senderId: MOCK_USER_ID,
      receiverId: 'user-2',
      text: 'Haha, gotta stand by it! What kind of art do you do?',
      timestamp: daysAgo(0, 0, 8),
    },
  ],
};

export const getCurrentUser = (): UserProfile => {
  const user = MOCK_USERS.find(user => user.id === MOCK_USER_ID);
  if (!user) {
    return {
        id: MOCK_USER_ID,
        name: "Current User",
        age: 30,
        bio: "Default bio for a user not found in mock data.",
        images: ['https://placehold.co/400x500.png'],
        vibeTags: ["default", "user"],
        prompts: [],
        email: 'user@example.com',
        work: 'Unknown Inc.',
        jobTitle: 'Default Position',
        education: 'University of Defaults',
        ethnicity: 'Prefer Not to Say',
        childrenStatus: 'Prefer Not to Say',
        familyPlans: 'Prefer Not to Say',
        height: 'Prefer Not to Say',
        drinking: 'Prefer Not to Say',
        smoking: 'Prefer Not to Say',
        zodiacSign: 'Prefer Not to Say',
        locationAddress: '123 Default Street, Default City',
        locationName: 'Default City',
        locationCoordinates: { lat: 0, lng: 0 },
        achievements: [],
        locationPatterns: ['cafes', 'parks']
    };
  }
  return user;
};

export const MOCK_CROSSED_PATHS_USERS: CrossedPathUser[] = MOCK_USERS.filter(u => u.id !== MOCK_USER_ID).map((user, index) => ({
  ...user,
  crossedAt: daysAgo(index + 0.1), 
  location: index % 3 === 0 ? 'The Shard' : (index % 3 === 1 ? 'Tate Modern' : 'British Museum'), 
}));

export const MOCK_HOTSPOTS: Hotspot[] = [
  {
    id: 'hs-1',
    type: 'Connection Zone',
    title: 'British Museum Area',
    description: '3 recent Moments were logged here this week.',
    coordinates: { lat: 51.5194, lng: -0.1270 },
  },
  {
    id: 'hs-2',
    type: 'Serendipity Spike',
    title: 'Near The Shard',
    description: 'This area had 2 Double Sparks today.',
    coordinates: { lat: 51.5055, lng: -0.0875 },
  },
  {
    id: 'hs-3',
    type: 'Loop Zone',
    title: 'Covent Garden Market',
    description: 'You’ve crossed paths with multiple users here before.',
    coordinates: { lat: 51.5118, lng: -0.1245 },
  },
  {
    id: 'hs-4',
    type: 'Serendipity Spike',
    title: 'Sky Garden Views',
    description: 'High-vibe connections are sparking here with the scenic views.',
    coordinates: { lat: 51.5109, lng: -0.0837 },
  },
  {
    id: 'hs-5',
    type: 'Connection Zone',
    title: 'Hyde Park Mornings',
    description: 'This area is emotionally charged on sunny mornings. Great for calm vibes.',
    coordinates: { lat: 51.5073, lng: -0.1657 },
    charge: 'morning',
  },
  {
    id: 'hs-6',
    type: 'Serendipity Spike',
    title: 'Soho Evenings',
    description: 'Sparks fly here after dark. High energy and frequent matches.',
    coordinates: { lat: 51.5132, lng: -0.1367 },
    charge: 'night',
  },
  {
    id: 'hs-7',
    type: 'Connection Zone',
    title: 'Historic Tower of London',
    description: 'A popular spot for history buffs. Many moments have been logged here recently.',
    coordinates: { lat: 51.5081, lng: -0.0759 },
  },
  {
    id: 'hs-8',
    type: 'Serendipity Spike',
    title: 'The Gherkin After Work',
    description: 'A hub of activity in the evenings. Sparks often fly here as the sun sets.',
    coordinates: { lat: 51.5145, lng: -0.0803 },
    charge: 'night',
  },
];
