import { QuestionNode, Vertical } from "../types";

const vertical: Vertical = "employment";

export const employmentQuestions: QuestionNode[] = [
  {
    id: "opening",
    text:
      "I’m sorry you’re dealing with this — being dismissed can be very stressful. I’ll ask a few questions to understand what happened.",
    field: "opening_ack",
    required: false,
    type: "text",
    vertical,
  },
  {
    id: "employment_status",
    text: "Were you an employee, worker, or self-employed contractor?",
    field: "employment_status",
    required: true,
    type: "enum",
    options: ["employee", "worker", "contractor", "unknown"],
    vertical,
  },
  {
    id: "length_of_service_band",
    text: "How long had you worked for the employer before your employment ended?",
    field: "length_of_service_band",
    required: true,
    type: "enum",
    options: ["<2y", ">=2y", "unknown", "<1y", "1-2y"],
    vertical,
  },
  {
    id: "dismissed_or_resigned",
    text: "Were you dismissed by the employer, or did you resign?",
    field: "dismissed_or_resigned",
    required: true,
    type: "enum",
    options: ["dismissed", "resigned", "unknown"],
    vertical,
  },
  {
    id: "dismissal_date",
    text: "When did your employment end?",
    field: "dismissal_date",
    required: true,
    type: "date",
    vertical,
    followup: {
      whenMissing: "Was this within the last 1 month, 3 months, or longer ago?",
    },
  },
  {
    id: "reason_given",
    text: "What reason were you given for your dismissal, if any?",
    field: "reason_given",
    required: true,
    type: "enum",
    options: ["misconduct", "performance", "redundancy", "capability", "no_reason", "unknown"],
    vertical,
  },
  {
    id: "process_followed",
    text: "Before you were dismissed, were you given any of the following?",
    field: "process_followed",
    required: true,
    type: "multi",
    options: [
      "written_allegations",
      "disciplinary_meeting",
      "opportunity_to_respond",
      "warnings",
      "right_of_appeal",
      "none",
    ],
    vertical,
  },
  {
    id: "documents_available",
    text: "Do you have any documents relating to the dismissal?",
    field: "documents_available",
    required: true,
    type: "enum",
    options: ["yes", "no", "unsure"],
    vertical,
  },
  {
    id: "automatic_unfair",
    text: "Do you believe the dismissal was related to discrimination, whistleblowing, health & safety, trade union activity, or asserting statutory rights?",
    field: "automatic_unfair",
    required: false,
    type: "multi",
    options: [
      "discrimination",
      "whistleblowing",
      "health_safety",
      "trade_union",
      "asserting_statutory_rights",
      "none",
    ],
    vertical,
  },
  {
    id: "current_status",
    text: "Are you currently employed elsewhere?",
    field: "current_status",
    required: false,
    type: "enum",
    options: ["yes", "no", "unknown"],
    vertical,
  },
  {
    id: "desired_outcome",
    text: "What outcome are you hoping for?",
    field: "desired_outcome",
    required: false,
    type: "text",
    vertical,
  },
];
